### ISSUE TITLE
A few suggestions (not really an issue)

### ISSUE THREAD

**Issue by anselm-urban** [peternerlich/BellCountdown#2]
- move script before closing body tag to increase loading speed
- leave out type="text/css" - it´s just not necessary anymore
- instead of `<meta http-equiv="Content-Type" content="text/html; charset=utf-8">` just use meta charset="utf-8" - it´s the HTML5 way of content encoding and works without compat issues
- probably leave out meta copyright since it was never described in any spec and has no effect at all
- make the timer unselectable (user-select: none)
- use vw units for making text full width
- make a minified production copy of timer.js (with Google Closure Compiler)

**Comment by PeterNerlich** [comment]
Thank you for your advise.
- I will leave the copyright meta in for now, who knows. I read it somewhere. If it does nothing, it can't break anything.
- I will stick with fitting the text vis JS because viewport units describe single characters. 20vw would fit on my system but I can't be sure every monospace font is the same here. Also the text should fit with little but super wide screens, too.
- I probably won't use minifying or similar changes that don't affect the code itself in this repository since it has no improvements while developing.
